import {randomUUID} from 'node:crypto'
import {promises as fs} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'

import {expect} from 'chai'
import {afterEach, beforeEach, describe, it} from 'mocha'

import {installBmad} from '../../src/lib/bmad-installer.js'
import {updateGitignore} from '../../src/lib/gitignore-manager.js'

describe('BMAD Installation Integration Tests', () => {
  let testDir: string

  beforeEach(async () => {
    // Create a unique temp directory for each test
    testDir = join(tmpdir(), `pai-bmad-test-${randomUUID()}`)
    await fs.mkdir(testDir, {recursive: true})
  })

  afterEach(async () => {
    // Clean up test directory
    try {
      await fs.rm(testDir, {force: true, recursive: true})
    } catch {
      // Ignore cleanup errors
    }
  })

  it('should install BMAD with complete directory structure', async function () {
    // Increase timeout for this test as it copies many files
    this.timeout(30_000)

    await installBmad({
      projectName: 'test-project',
      targetDir: testDir,
      username: 'TestUser',
    })

    // Verify directory structure created
    const bmadDir = join(testDir, '_bmad')
    expect(await pathExists(bmadDir)).to.be.true

    // Verify core module
    const coreDir = join(bmadDir, 'core')
    expect(await pathExists(coreDir)).to.be.true
    expect(await pathExists(join(coreDir, 'config.yaml'))).to.be.true
    expect(await pathExists(join(coreDir, 'agents'))).to.be.true
    expect(await pathExists(join(coreDir, 'workflows'))).to.be.true

    // Verify BMM module
    const bmmDir = join(bmadDir, 'bmm')
    expect(await pathExists(bmmDir)).to.be.true
    expect(await pathExists(join(bmmDir, 'config.yaml'))).to.be.true
    expect(await pathExists(join(bmmDir, 'agents'))).to.be.true
    expect(await pathExists(join(bmmDir, 'workflows'))).to.be.true

    // Verify _config directory
    const configDir = join(bmadDir, '_config')
    expect(await pathExists(configDir)).to.be.true
    expect(await pathExists(join(configDir, 'manifest.yaml'))).to.be.true
    expect(await pathExists(join(configDir, 'agent-manifest.csv'))).to.be.true
    expect(await pathExists(join(configDir, 'workflow-manifest.csv'))).to.be.true

    // Verify output directories
    const outputDir = join(testDir, '_bmad-output')
    expect(await pathExists(outputDir)).to.be.true
    expect(await pathExists(join(outputDir, 'planning-artifacts'))).to.be.true
    expect(await pathExists(join(outputDir, 'implementation-artifacts'))).to.be.true

    // Verify .claude/commands/bmad structure
    const claudeCommandsDir = join(testDir, '.claude', 'commands', 'bmad')
    expect(await pathExists(claudeCommandsDir)).to.be.true
    expect(await pathExists(join(claudeCommandsDir, 'core'))).to.be.true
    expect(await pathExists(join(claudeCommandsDir, 'bmm'))).to.be.true
    expect(await pathExists(join(claudeCommandsDir, 'core', 'agents'))).to.be.true
    expect(await pathExists(join(claudeCommandsDir, 'bmm', 'agents'))).to.be.true
    expect(await pathExists(join(claudeCommandsDir, 'bmm', 'workflows'))).to.be.true
  })

  it('should generate custom configuration files', async function () {
    this.timeout(30_000)

    await installBmad({
      projectName: 'my-project',
      targetDir: testDir,
      username: 'Alice',
    })

    // Verify core config contains custom values
    const coreConfig = await fs.readFile(join(testDir, '_bmad', 'core', 'config.yaml'), 'utf8')
    expect(coreConfig).to.include('Generated by PAI CLI')
    expect(coreConfig).to.include('user_name: Alice')
    expect(coreConfig).to.include('6.0.0-alpha.22')

    // Verify BMM config contains custom values
    const bmmConfig = await fs.readFile(join(testDir, '_bmad', 'bmm', 'config.yaml'), 'utf8')
    expect(bmmConfig).to.include('Generated by PAI CLI')
    expect(bmmConfig).to.include('project_name: my-project')
    expect(bmmConfig).to.include('user_name: Alice')

    // Verify manifest
    const manifest = await fs.readFile(join(testDir, '_bmad', '_config', 'manifest.yaml'), 'utf8')
    expect(manifest).to.include('installedBy: pai-cli')
    expect(manifest).to.include('version: 6.0.0-alpha.22')
  })

  it('should create .gitignore with BMAD patterns when it does not exist', async () => {
    await updateGitignore(testDir, ['_bmad', '_bmad-output', 'bmad-output', '**/bmad-output'])

    const gitignore = await fs.readFile(join(testDir, '.gitignore'), 'utf8')
    expect(gitignore).to.include('# PAI Installation')
    expect(gitignore).to.include('_bmad/')
    expect(gitignore).to.include('_bmad-output/')
    expect(gitignore).to.include('bmad-output/')
  })

  it('should append to existing .gitignore without duplication', async () => {
    const existingContent = '# My project\nnode_modules/\ndist/\n'
    await fs.writeFile(join(testDir, '.gitignore'), existingContent, 'utf8')

    await updateGitignore(testDir, ['_bmad', '_bmad-output'])

    const gitignore = await fs.readFile(join(testDir, '.gitignore'), 'utf8')

    // Should preserve existing content
    expect(gitignore).to.include('# My project')
    expect(gitignore).to.include('node_modules/')
    expect(gitignore).to.include('dist/')

    // Should add PAI patterns
    expect(gitignore).to.include('# PAI Installation')
    expect(gitignore).to.include('_bmad/')
  })

  it('should not duplicate PAI patterns if already present', async () => {
    const existingContent = '# My project\nnode_modules/\n\n# PAI Installation\n_bmad/\n_bmad-output/\n'
    await fs.writeFile(join(testDir, '.gitignore'), existingContent, 'utf8')

    await updateGitignore(testDir, ['_bmad', '_bmad-output'])

    const gitignore = await fs.readFile(join(testDir, '.gitignore'), 'utf8')

    // Should not add duplicate patterns
    const matches = gitignore.match(/# PAI Installation/g)
    expect(matches).to.have.lengthOf(1, 'PAI patterns should only appear once')
  })

  it('should install agents from template', async function () {
    this.timeout(30_000)

    await installBmad({
      projectName: 'test-project',
      targetDir: testDir,
      username: 'TestUser',
    })

    // Verify BMM agents exist
    const bmmAgentsDir = join(testDir, '_bmad', 'bmm', 'agents')
    const agentFiles = await fs.readdir(bmmAgentsDir)

    // Should have multiple agents
    expect(agentFiles.length).to.be.greaterThan(0)

    // Check for key agents
    expect(agentFiles.some((f) => f.includes('dev'))).to.be.true
    expect(agentFiles.some((f) => f.includes('pm'))).to.be.true
  })

  it('should install workflows from template', async function () {
    this.timeout(30_000)

    await installBmad({
      projectName: 'test-project',
      targetDir: testDir,
      username: 'TestUser',
    })

    // Verify BMM workflows exist
    const bmmWorkflowsDir = join(testDir, '_bmad', 'bmm', 'workflows')
    expect(await pathExists(bmmWorkflowsDir)).to.be.true

    // Check for workflow directories
    const workflowDirs = await fs.readdir(bmmWorkflowsDir)
    expect(workflowDirs.length).to.be.greaterThan(0)

    // Should have implementation phase
    expect(workflowDirs.some((f) => f.includes('implementation'))).to.be.true
  })
})

/**
 * Helper to check if path exists
 */
async function pathExists(path: string): Promise<boolean> {
  try {
    await fs.access(path)
    return true
  } catch {
    return false
  }
}
