import {execSync} from 'node:child_process'
import {promises as fs} from 'node:fs'
import {join} from 'node:path'

import {getBmadTemplatePath} from './template-resolver.js'

/**
 * BMAD version to install
 */
const BMAD_VERSION = '6.0.0-alpha.22'

/**
 * BMAD installation configuration
 */
export interface BmadInstallConfig {
  projectName: string
  targetDir: string
  username: string
}

/**
 * Generate core module configuration YAML
 */
export function generateCoreConfig(username: string): string {
  const now = new Date().toISOString()
  return `# CORE Module Configuration
# Generated by PAI CLI
# Version: ${BMAD_VERSION}
# Date: ${now}

user_name: ${username}
communication_language: English
document_output_language: English
output_folder: "{project-root}/_bmad-output"
`
}

/**
 * Generate BMM module configuration YAML
 */
export function generateBmmConfig(projectName: string, username: string): string {
  const now = new Date().toISOString()
  return `# BMM Module Configuration
# Generated by PAI CLI
# Version: ${BMAD_VERSION}
# Date: ${now}

project_name: ${projectName}
user_skill_level: intermediate
planning_artifacts: "{project-root}/_bmad-output/planning-artifacts"
implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
project_knowledge: "{project-root}/docs"
tea_use_mcp_enhancements: false
tea_use_playwright_utils: false

# Core Configuration Values
user_name: ${username}
communication_language: English
document_output_language: English
output_folder: "{project-root}/_bmad-output"
`
}

/**
 * Generate installation manifest YAML
 */
export function generateManifest(): string {
  const now = new Date().toISOString()
  return `installation:
  version: ${BMAD_VERSION}
  installDate: ${now}
  lastUpdated: ${now}
  installedBy: pai-cli
modules:
  - core
  - bmm
ides:
  - claude-code
`
}

/**
 * Copy directory recursively with proper error handling
 */
async function copyDir(src: string, dest: string): Promise<void> {
  await fs.mkdir(dest, {recursive: true})

  const entries = await fs.readdir(src, {withFileTypes: true})

  const operations = entries.map(async (entry) => {
    const srcPath = join(src, entry.name)
    const destPath = join(dest, entry.name)

    return entry.isDirectory() ? copyDir(srcPath, destPath) : fs.copyFile(srcPath, destPath)
  })

  await Promise.all(operations)
}

/**
 * Install BMAD structure in target directory
 */
export async function installBmad(config: BmadInstallConfig): Promise<void> {
  const {projectName, targetDir, username} = config

  // Get bundled BMAD template path (parent directory containing _bmad/ and .claude/)
  const templateRootPath = getBmadTemplatePath()

  // Verify template exists
  try {
    await fs.access(templateRootPath)
  } catch {
    throw new Error(
      `BMAD template not found at ${templateRootPath}. ` +
      `This indicates a corrupted installation. Please reinstall pai-cli.`
    )
  }

  const bmadPath = join(targetDir, '_bmad')
  const claudePath = join(targetDir, '.claude')

  // Create main _bmad directories
  await fs.mkdir(join(bmadPath, '_config'), {recursive: true})
  await fs.mkdir(join(bmadPath, 'core'), {recursive: true})
  await fs.mkdir(join(bmadPath, 'bmm'), {recursive: true})

  // Create output directories
  await fs.mkdir(join(targetDir, '_bmad-output', 'planning-artifacts'), {recursive: true})
  await fs.mkdir(join(targetDir, '_bmad-output', 'implementation-artifacts'), {recursive: true})

  // Copy _bmad/ structure from template
  const templateBmadPath = join(templateRootPath, '_bmad')

  // Copy core module from template
  const templateCorePath = join(templateBmadPath, 'core')
  const targetCorePath = join(bmadPath, 'core')
  await copyDir(templateCorePath, targetCorePath)

  // Copy BMM module from template
  const templateBmmPath = join(templateBmadPath, 'bmm')
  const targetBmmPath = join(bmadPath, 'bmm')
  await copyDir(templateBmmPath, targetBmmPath)

  // Copy _config directory (manifest CSVs, ides, etc.) from template
  const templateConfigPath = join(templateBmadPath, '_config')
  const targetConfigPath = join(bmadPath, '_config')
  await copyDir(templateConfigPath, targetConfigPath)

  // Copy .claude/commands/bmad/ structure from template
  const templateClaudeBmadPath = join(templateRootPath, '.claude', 'commands', 'bmad')
  const targetClaudeBmadPath = join(claudePath, 'commands', 'bmad')
  await copyDir(templateClaudeBmadPath, targetClaudeBmadPath)

  // Generate and write custom configuration files (overwrite template configs)
  await fs.writeFile(join(targetCorePath, 'config.yaml'), generateCoreConfig(username), 'utf8')
  await fs.writeFile(join(targetBmmPath, 'config.yaml'), generateBmmConfig(projectName, username), 'utf8')
  await fs.writeFile(join(targetConfigPath, 'manifest.yaml'), generateManifest(), 'utf8')
}

/**
 * Update .gitignore with BMAD patterns
 */
export async function updateGitignore(targetDir: string): Promise<void> {
  const gitignorePath = join(targetDir, '.gitignore')

  const bmadPatterns = `
# BMAD Installation
_bmad/
_bmad-output/
bmad-output/
**/bmad-output/
`

  try {
    // Try to read existing .gitignore
    const existing = await fs.readFile(gitignorePath, 'utf8')

    // Check if BMAD patterns already present
    if (existing.includes('# BMAD Installation') || existing.includes('_bmad/')) {
      return // Already has BMAD patterns
    }

    // Append patterns
    await fs.writeFile(gitignorePath, existing + '\n' + bmadPatterns, 'utf8')
  } catch {
    // .gitignore doesn't exist, create it
    await fs.writeFile(gitignorePath, bmadPatterns.trim() + '\n', 'utf8')
  }
}

/**
 * Detect username from git config or environment variables.
 * Priority: git config user.name > USER env > USERNAME env > fallback to "User"
 */
export async function detectUsername(): Promise<string> {
  // Try git config first
  try {
    const gitUser = execSync('git config user.name', {encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe']})
    const username = gitUser.trim()
    if (username) return username
  } catch {
    // Git command failed or not configured, continue to env vars
  }

  // Try environment variables
  const envUser = process.env['USER'] ?? process.env['USERNAME']
  if (envUser) return envUser

  // Fallback
  return 'User'
}
